# Generated by Django 5.0.6 on 2024-06-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_dues_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='loan_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='unique_user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
