# Generated by Django 5.0.6 on 2024-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_dues_loan_id_alter_loan_unique_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='minimum_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
