# Generated by Django 5.0.6 on 2024-06-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_minimum_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dues',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='dues',
            name='loan',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
            preserve_default=False,
        ),
    ]
