# Generated by Django 5.0.6 on 2024-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_billing_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='past_due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
