# Generated by Django 5.0.6 on 2024-06-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
